tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/services"

brew "ack"
brew "bat"
brew "bottom"
brew "coreutils"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "gnupg"
brew "graphicsmagick"
brew "jq"
brew "mas"
brew "micromamba"
brew "neovim"
brew "openconnect"
brew "ripgrep"
brew "safe-rm"
brew "starship"
brew "tmux"
brew "vcpkg"
brew "wget"
brew "zoxide"

cask "1password-cli"
cask "alacritty"
cask "bookends"
cask "latexit"
cask "mactex-no-gui"
cask "rectangle"
cask "skim"
cask "visual-studio-code"

mas "Aware", id: 1082170746
mas "Craft", id: 1487937127
mas "DaisyDisk", id: 411643860
mas "Keynote", id: 409183694
mas "Slack", id: 803453959
mas "Texifier", id: 458866234
mas "Things", id: 904280696
