[character]
success_symbol = "λ(bold green)"
error_symbol = "λ(bold red)"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[git_status]
disabled = false

[git_branch]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[ruby]
disabled = true

[php]
disabled = true

[package]
disabled = true

[java]
disabled = true

[conda]
disabled = true

[aws]
disabled = true

[hg_branch]
disabled = true

[golang]
disabled = true
