format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$time\
$line_break\
$character
"""
right_format="""
$python\
$node_js\
$conda
"""

[character]
success_symbol = "[](#9ece6a)"
error_symbol = "[](red)"
vimcmd_symbol = "[](#7aa2f7)"
vimcmd_visual_symbol = "[](#bb9af7)"
vimcmd_replace_symbol = "[](#f7768e)"
vimcmd_replace_one_symbol = "[](#f7768e)"

[time]
disabled=false
format = ' [$time]($style)'
style = 'bold yellow'
use_12hr = true

[fill]
symbol = '·'
style = '#3b4261'

[directory]
read_only = " "
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[conda]
format = '[$symbol$environment]($style)'
symbol = " "

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "#89ddff bold"

[git_branch]
disabled = false
format = "on [$symbol$branch]($style) "
symbol = " "
style = "bold purple"
truncation_symbol = "…"

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red bold"
stashed = '\$'
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"

[git_state]
disabled = false
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
