[character]
success_symbol = "λ(bold green)"
error_symbol = "λ(bold red)"

[aws]
disabled = true
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled = true
symbol = " "

[git_status]
disabled = true
[git_branch]
symbol = " "

[golang]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
symbol = " "
