live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1D202F"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 14

[font.bold]
family = "ComicCodeLigatures Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicCodeLigatures Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "ComicCodeLigatures Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font"

[font.offset]
x = 0
y = 0

[scrolling]
history = 0
multiplier = 3

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux -2 new-session -A -s default"]

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
opacity = 0.985
blur = true

[window.dimensions]
columns = 115
lines = 35

[window.padding]
x = 20
y = 30
